# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cluster.proto for package 'anndb_pb'

require 'grpc'
require 'cluster_pb'

module AnndbPb
  module NodesManager
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'anndb_pb.NodesManager'

      rpc :ListNodes, EmptyMessage, stream(Node)
      rpc :AddNode, Node, stream(Node)
      rpc :RemoveNode, Node, EmptyMessage
    end

    Stub = Service.rpc_stub_class
  end
end
