# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("core.proto", :syntax => :proto3) do
    add_message "anndb_pb.EmptyMessage" do
    end
    add_message "anndb_pb.UUIDRequest" do
      optional :id, :bytes, 1
    end
  end
end

module AnndbPb
  EmptyMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("anndb_pb.EmptyMessage").msgclass
  UUIDRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("anndb_pb.UUIDRequest").msgclass
end
