# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: raft.proto for package 'anndb_pb'

require 'grpc'
require 'raft_pb'

module AnndbPb
  module RaftTransport
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'anndb_pb.RaftTransport'

      rpc :Receive, RaftMessage, EmptyMessage
    end

    Stub = Service.rpc_stub_class
  end
end
